version: '3'
services:
  nginx:
    build: nginx
    ports:
      - "8080:80"
    volumes:
      - ./application:/var/www/html
    networks:
      - interna
  php:
    build: php
    volumes:
      - ./application:/var/www/html
    networks:
      - interna
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: local
      MYSQL_USER: batoi
      MYSQL_PASSWORD: 1234
    ports:
      - "33061:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - interna
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        networks: 
            - interna
        ports:
            - 8081:80
        environment:
           PMA_HOST: mysql
           PMA_PORT: 3306
  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data
    networks:
      - interna
networks:
  interna:
    driver: "bridge"
volumes:
  redisdata:
    driver: "local"
  mysqldata:
    driver: "local"
